name: Komunikacja Techniczna, Akademia Finansów i Biznesu Vistula
title: Morris Mini Owner's Manual
description: An example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: vistula

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/morris-mini"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on <a href=\"https://github.com/flicstar/DITA-Mini-Manual\">Felicity Brand's example DITA project.</a>"